[climate]
climate_record_path=E:\气象站点\江苏全部气象站点\肖一嘉大好人\气象站点 - 副本
station_file_name=E:\气象站点\江苏全部气象站点\肖一嘉大好人\position.csv
needfields=radn;maxt;mint;rain
output_path=E:\气象站点\江苏全部气象站点\肖一嘉大好人\result

[grid]
field_paths=E:\rain;E:\maxt;E:\radn
output_path=result