[climate]
climate_record_path=E:\气象站点\江苏全部气象站点\肖一嘉大好人\气象站点 - 副本
station_file_name=E:\气象站点\江苏全部气象站点\肖一嘉大好人\position.csv
needfields=radn;maxt;mint;rain
output_path=E:\气象站点\江苏全部气象站点\肖一嘉大好人\result

[grid]
radn_path=E:\radn
rain_paht=E:\rain
tmax_path=E:\Tmax
tmin_path=E:\Tmin
output_path=result